### PR TITLE
Skal bruke node 18

### PR DESCRIPTION
**Pull request by charliemidtlyng**
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-10245)

### CODE REVIEW

**Review by blommish — APPROVED** [review]
Så enkelt 👀

**Comment by blommish** [comment]
Burde vi legge til setup-node til ettersending?
Likt denne https://github.com/navikt/familie-ef-veiviser/pull/450/files#diff-d0777657fa3fd81d23aaf7273e58aee453b04e67882517900c56daeef9b3e4c1R11

**Comment by charliemidtlyng** [comment]
> Burde vi legge til setup-node til ettersending? Likt denne https://github.com/navikt/familie-ef-veiviser/pull/450/files#diff-d0777657fa3fd81d23aaf7273e58aee453b04e67882517900c56daeef9b3e4c1R11

Kanskje, men ikke i denne PR-en

**Comment by charliemidtlyng** [comment]
Testet i preprod ✅

**Pull request merged**
